apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "BedrockMySQL2025!"
        - name: MYSQL_DATABASE
          value: "ordersdb"
        - name: MYSQL_USER
          value: "dbadmin"
        - name: MYSQL_PASSWORD
          value: "BedrockMySQL2025!"
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 512m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: retail-app
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "catalogdb"
        - name: POSTGRES_USER
          value: "dbadmin"
        - name: POSTGRES_PASSWORD
          value: "BedrockPG2025!"
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 512m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: retail-app
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
